apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  labels:
    app: glosleep
    tier: backend
    service: analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
        app.kubernetes.io/name: analytics-service
        app.kubernetes.io/part-of: glosleep-platform
    spec:
      containers:
      - name: analytics-service
        image: analytics-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3004
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_ANALYTICS_URI
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"