apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: glosleep
    tier: backend
    service: inventory
spec:
  selector:
    app: inventory-service
  ports:
  - port: 80
    targetPort: 3001
  type: ClusterIP