apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: glosleep
    tier: backend
    service: order
spec:
  selector:
    app: order-service
  ports:
  - port: 80
    targetPort: 3002
  type: ClusterIP