apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: glosleep
    tier: backend
    service: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        app.kubernetes.io/name: order-service
        app.kubernetes.io/part-of: glosleep-platform
    spec:
      containers:
      - name: order-service
        image: docker.io/anshumandash1506/glosleep-order-service:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_ORDER_URI
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"