apiVersion: v1
kind: Service
metadata:
  name: procurement-service
  labels:
    app: glosleep
    tier: backend
    service: procurement
spec:
  selector:
    app: procurement-service
  ports:
  - port: 80
    targetPort: 3003
  type: ClusterIP